services:
  simple-ai-writer:
    container_name: simple-ai-writer
    restart: always
    
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: local/simple-ai-writer
    pull_policy: never

    ports:
      - "3000:3000"
    environment:
      - UID=1000
      - GID=1000
      - NODE_ENV=production
    volumes:
      - ./data:/app/data

    logging:
      driver:  json-file
      options:
        max-file: "3"
        max-size: "10M"
